### PR TITLE
PRM comparison update

### PR DESCRIPTION
**Pull request by wrangelvid**
Switched to a much faster C++ implementation of PRM.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mpetersen94/gcs/49)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
I didn't review every line of the changes, but the ones I did looked reasonable.  I ran both updated notebooks on my machine to confirm the results.  

Btw -- i can tell that your forked drake is not fully up to date.  For instance, mosek still spews license errors.  Probably it's worth updating?

> Reviewed 3 of 4 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mpetersen94/gcs/49#-:-N_sd8IGCo7Kbbr-C6n6:b-yv9xh7)* status: all files reviewed, 2 unresolved discussions (waiting on @wrangelvid)

___
*[`reproduction/prm_comparison/helpers.py` line 95 at r2](https://reviewable.io/reviews/mpetersen94/gcs/49#-N_sfoZMEQxTkywDPKsI:-N_sfoZMEQxTkywDPKsJ:bvbagot) ([raw file](https://github.com/mpetersen94/gcs/blob/b3f92de7e60eb119349cbf1f20a749d65f363624/reproduction/prm_comparison/helpers.py#L95)):*
> ```Python
>     return q1
> 
> def lower_alpha(plant, inspector, model_instances, alpha, scene_graph):
> ```

this caused 
```
ImportError: cannot import name 'lower\_alpha' from 'reproduction.prm\_comparison.helpers' (/home/russt/tmp/gcs/reproduction/prm\_comparison/helpers.py)
``` in the bimanual notebook.
```

___
*[`reproduction/prm_comparison/prm_comparison.ipynb` line 47 at r2](https://reviewable.io/reviews/mpetersen94/gcs/49#-N_sf8BR2HPeHnqh9o4s:-N_sf8BR2HPeHnqh9o4t:b-tqa9ml) ([raw file](https://github.com/mpetersen94/gcs/blob/81a3f8a3c36da193c0e0cfcbb9116cd11d58ade8/reproduction/prm_comparison/prm_comparison.ipynb#L47)):*
> ```
>     "\n",
>     "GurobiSolver.AcquireLicense()\n",
>     "MosekSolver.AcquireLicense()"
> ```

these are not doing what you think.  you need to hold on to the return value... e.g.
```
# Acquire a Gurobi license once (to avoid constantly reaquiring it).
gurobi = GurobiSolver()
if gurobi.available() and gurobi.enabled():
    gurobi_license = gurobi.AcquireLicense()
```

(this is wrong in all of the notebooks; once fixed, it should avoid the solver license spew).

**Comment by RussTedrake** [comment]
(update.... it's gurobi that spews those errors)... which can be fixed either by updating Drake or by fixing the AcquireLicense bits below.

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mpetersen94/gcs/49)* status: all files reviewed, 2 unresolved discussions (waiting on @wrangelvid)

___
*[`reproduction/prm_comparison/prm_comparison.ipynb` line 47 at r2](https://reviewable.io/reviews/mpetersen94/gcs/49#-N_sf8BR2HPeHnqh9o4s:-N_sgCY9EoTEqMJ_cyug:b-buirbn) ([raw file](https://github.com/mpetersen94/gcs/blob/81a3f8a3c36da193c0e0cfcbb9116cd11d58ade8/reproduction/prm_comparison/prm_comparison.ipynb#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

these are not doing what you think.  you need to hold on to the return value... e.g.
```
# Acquire a Gurobi license once (to avoid constantly reaquiring it).
gurobi = GurobiSolver()
if gurobi.available() and gurobi.enabled():
    gurobi_license = gurobi.AcquireLicense()
```

(this is wrong in all of the notebooks; once fixed, it should avoid the solver license spew).
</blockquote></details>

I guess you just want
```
gurobi_license = GurobiSolver.AcquireLicense()
```
because you want to force the user to have those licenses.

**Review by wrangelvid — COMMENTED** [review]
We should absolutely update my drake fork. I wanted to hold off until the rounding improvments land to the `GraphOfconvexSets` class in drake.

> *[Reviewable](https://reviewable.io/reviews/mpetersen94/gcs/49#-:-N_y-0GL3CeqNyqSDZLP:bqkf4bw)* status: all files reviewed, 2 unresolved discussions (waiting on @RussTedrake)

___
*[`reproduction/prm_comparison/helpers.py` line 95 at r2](https://reviewable.io/reviews/mpetersen94/gcs/49#-N_sfoZMEQxTkywDPKsI:-N_xzYuqDtisRl2nCz07:b6zrrkh) ([raw file](https://github.com/mpetersen94/gcs/blob/b3f92de7e60eb119349cbf1f20a749d65f363624/reproduction/prm_comparison/helpers.py#L95)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this caused 
```
ImportError: cannot import name 'lower\_alpha' from 'reproduction.prm\_comparison.helpers' (/home/russt/tmp/gcs/reproduction/prm\_comparison/helpers.py)
``` in the bimanual notebook.
```

</blockquote></details>

Good catch.
___
*[`reproduction/prm_comparison/prm_comparison.ipynb` line 47 at r2](https://reviewable.io/reviews/mpetersen94/gcs/49#-N_sf8BR2HPeHnqh9o4s:-N_xzuzyC7mgGpaN-SEs:b-896fix) ([raw file](https://github.com/mpetersen94/gcs/blob/81a3f8a3c36da193c0e0cfcbb9116cd11d58ade8/reproduction/prm_comparison/prm_comparison.ipynb#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I guess you just want
```
gurobi_license = GurobiSolver.AcquireLicense()
```
because you want to force the user to have those licenses.
</blockquote></details>

Done.

**Review by RussTedrake — APPROVED** [review]
Those landed sometime last week.  but it's true that iris is getting better with open PRs, too.
Running against the latest IRIS actually spews warnings that we might want to take seriously in the bimanual example...  sphere are probably not the best/right collision geometry...?

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mpetersen94/gcs/49#-:-Na2CMDB9CgACn7rticL:bdy7ait)* status: all files reviewed, 1 unresolved discussion (waiting on @wrangelvid)

___
*[`reproduction/bimanual/bimanual_iiwa_example.ipynb` line 161 at r3](https://reviewable.io/reviews/mpetersen94/gcs/49#-Na2I0Jr8CsCfykc24nJ:-Na2I0Js6e7bkJ2cNnxF:bq0zmgm) ([raw file](https://github.com/mpetersen94/gcs/blob/77216c8fe5337f11d2898c586ff12a54dafb6202/reproduction/bimanual/bimanual_iiwa_example.ipynb#L161)):*
> ```
>    "outputs": [],
>    "source": [
>     "with open(os.path.join(GcsDir(), 'data/bimanual/iris_regions.reg'), 'rb') as f:\n",
> ```

btw -- did you want to save these regions in the data directory, too?  it seems like a good idea.
___
*[`reproduction/prm_comparison/prm_comparison.ipynb` line 47 at r2](https://reviewable.io/reviews/mpetersen94/gcs/49#-N_sf8BR2HPeHnqh9o4s:-Na2Co8f-E2K8-Kv9mXR:baaigmu) ([raw file](https://github.com/mpetersen94/gcs/blob/81a3f8a3c36da193c0e0cfcbb9116cd11d58ade8/reproduction/prm_comparison/prm_comparison.ipynb#L47)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

but can you fix it in the other notebooks, too... please?

**Review by wrangelvid — COMMENTED** [review]
Interesting. We can open an issue for that. At the moment, the code here will reproduce the work in the paper well. I believe there are many improvements we can land, which would improve the runtime and performance by a lot. However, maybe we should consider a different location that contains the most recent engineering efforts. E.g. a place using GcsTrajectoryOptimization would be nice, but shouldn't be used in this repository.

> *[Reviewable](https://reviewable.io/reviews/mpetersen94/gcs/49#-:-Na3u6B29NFvJSiykSsw:b-48iqx1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wrangelvid)

___
*[`reproduction/bimanual/bimanual_iiwa_example.ipynb` line 161 at r3](https://reviewable.io/reviews/mpetersen94/gcs/49#-Na2I0Jr8CsCfykc24nJ:-Na3u2P8AU000RQdYWEZ:b7n1a5y) ([raw file](https://github.com/mpetersen94/gcs/blob/77216c8fe5337f11d2898c586ff12a54dafb6202/reproduction/bimanual/bimanual_iiwa_example.ipynb#L161)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- did you want to save these regions in the data directory, too?  it seems like a good idea.
</blockquote></details>

Good idea. I will ping Mark for the original regions. It will be separate PR.
___
*[`reproduction/prm_comparison/prm_comparison.ipynb` line 47 at r2](https://reviewable.io/reviews/mpetersen94/gcs/49#-N_sf8BR2HPeHnqh9o4s:-Na3u1DODY7wHSOiybc1:b-896fix) ([raw file](https://github.com/mpetersen94/gcs/blob/81a3f8a3c36da193c0e0cfcbb9116cd11d58ade8/reproduction/prm_comparison/prm_comparison.ipynb#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

but can you fix it in the other notebooks, too... please?  
</blockquote></details>

Done.

**Pull request merged**
